### ISSUE TITLE
Compilation error on windows

### ISSUE THREAD

**Issue by kelevra89** [irungentoo/filter_audio#14]
I run into following error while trying to compile filter_audio on windows:

    make install
    LD    libfilteraudio.dll
    Can't open .lib file:
    collect2.exe: error: ld returned 1 exit status
    make: *** [libfilteraudio.dll] Error 1

Strange is, that the error doesn't show which .lib file couldn't be opened.

Compiler is gcc 4.8.1, mingw32

**Comment by ReDetection** [comment]
Yea, I think this is related to #12. I'll take care about that (in sparse time, so this might take a couple of days. You might want to checkout 6b4db1b8a4d0059078d5dc017a9ca34cce522f70 as quick solution)

**Comment by kelevra89** [comment]
Thanks, works like a charm!
