### ISSUE TITLE
Please create a stable release

### ISSUE THREAD

**Issue by farseerfc** [irungentoo/filter_audio#35]
Downstream distributions need these releases to make stable packages.
It is sufficient to give a version number like 0.0.1 .
Thank you~

**Comment by kyrias** [comment]
:+1:, have waited for this for quite a while.

**Comment by ShalokShalom** [comment]
Agree.

**Comment by NicoHood** [comment]
I really would also like to see a tagged release. Please also sign it with gpg so the download can be verified.

**Comment by kyrias** [comment]
After a year of no responses I've pretty much given up…

**Comment by GrayHatter** [comment]
Ask you you shall receive  https://github.com/irungentoo/filter_audio/releases/tag/v0.0.1

**Comment by NicoHood** [comment]
@farseerfc You can close this now :)

**Comment by farseerfc** [comment]
Thanks for the tag. @NicoHood and thanks for all the efforts.
