### ISSUE TITLE
Using filter_audio as pipe stream filter

### ISSUE THREAD

**Issue by UralZima** [irungentoo/filter_audio#38]
Hello. I am searching for a way to filter noise of laptop fan from my microphone input.
Does this library doing it? or just echo cancellation?

I am not C/C++ dev, but want to use this lib to filter a pipe stream, like:
arecord -f cd -t wav | ./filter_stream | mplayer -
How is hard to change the test program to act like this? Does it use some buffers? I want to understand, if I will be able to do that or search for another way... 
thanks

**Comment by GrayHatter** [comment]
I'm sure you could write something that would do this. I don't know of any that already exist.

IIRC filter audio works by filtering out the frequencies of sound that most human voices don't use. It can also do echo cancellation if you can get good timings out of your sound system.

That said, buying a cheap 10$ external mic is likely to be the best all around solution if it's an option.

**Comment by UralZima** [comment]
Thanks for answer. 
You know, I tried so many things to get clear sound. I bought external mic and used with my laptop internal card. Then I bought external Creative Play USB sound card. Then a logitech headset with built-in sound card. Very big noise in all cases. Only disconnecting laptop from AC and running on battery finally removed the noise :)

**Comment by UralZima** [comment]
And finally, if anybody will want to do this, SOX helped me.
Write 1.5sec of noise from test.mp3, create profile
$ sox test.mp3 -t null /dev/null trim 0 1.5 noiseprof ~/noiseprofile
$ play test.mp3 noisered ~/noiseprofile
Sox can do pipes and delete noise in real time.

**Comment by GrayHatter** [comment]
@UralZima you're awesome for coming back to close this issue with a well explained solution!

Thanks mate!
